### ISSUE TITLE
AddOrUpdate throws zombie exception

### ISSUE THREAD

**Issue by chinarosesz** [tiagoln/BulkExtensions#16] opened 2017-06-08 01:56 UTC
I'm currently falling back to Insert and Delete for now if there are duplicates, but I keep on getting this error when I try to upsert the below number of records.

```
[06/08/2017 01:34:41 > 73b0b5: INFO] 11332 commits found

[06/08/2017 01:34:41 > 73b0b5: INFO] Upserting records...

[06/08/2017 01:35:48 > 73b0b5: ERR ] 

[06/08/2017 01:35:48 > 73b0b5: ERR ] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at System.Data.SqlClient.SqlTransaction.ZombieCheck()

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at System.Data.SqlClient.SqlTransaction.Rollback()

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at EntityFramework.BulkExtensions.Commons.Context.DbContextWrapper.Rollback()

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at EntityFramework.BulkExtensions.Commons.BulkOperations.BulkInsertOrUpdate.EntityFramework.BulkExtensions.Commons.BulkOperations.IBulkOperation.CommitTransaction[TEntity](IDbContextWrapper context, IEnumerable`1 collection, BulkOptions options)

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at EntityFramework.BulkExtensions.BulkExtensions.BulkInsertOrUpdate[TEntity](DbContext context, IEnumerable`1 entities, InsertOptions options)

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at VsoCommitPump.CommitPump.UpsertCommits(List`1 commitsFromVso, TeamProjectReference project, GitRepository repository)

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at VsoCommitPump.CommitPump.<Run>d__0.MoveNext()

[06/08/2017 01:35:48 > 73b0b5: ERR ]    --- End of inner exception stack trace ---

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

[06/08/2017 01:35:48 > 73b0b5: ERR ]    at VsoCommitPump.Program.Main(String[] args)

[06/08/2017 01:35:48 > 73b0b5: SYS INFO] Status changed to Failed

[06/08/2017 01:35:48 > 73b0b5: SYS ERR ] Job failed due to exit code -532462766

```

**Comment by tiagoln** [comment] 2017-06-08 03:17
There are two things here:
#### First: The cause of the 'zombie exception'
This exception occurred because the BulkInsertOrUpdate operation failed with an exception, when this occurs, the library's standard procedure is to Rollback the transaction and throws up the exception for your code to handle. 

However, In this case the transaction had already been closed and was no longer usable when the library called the Rollback, thus throwing a new exception with this message: This SqlTransaction has completed; it is no longer usable. This is the cause of this "zombie exception", it's a bug, the library should not try to rollback a no longer available transaction, I'll fix the code to prevent this from happening.

#### Second
Now, as for what cause the original exception that triggered the Rollback attempt, I'm clueless, as this 'zombie exception' overshadowed the original exception.

**Comment by tiagoln** [comment] 2017-06-23 13:36
The "zombie exception" has been fixed on the new version, check it out.

**Closed by tiagoln** 2017-06-23 13:36 UTC
Labels: bug
