### ISSUE TITLE
How to give composite key when BulkInsertOrUpdate() ?

### ISSUE THREAD

**Issue by ferittuncer** [tiagoln/BulkExtensions#44] opened 2017-09-20 09:51 UTC
I'm trying to convert this

```
foreach (var pipe in pipes)
{
    context.Pipes.AddOrUpdate(p => new { p.MaterialName, p.ScheduleCode, p.NominalSizeInches }, pipe);
}
```

to this:

```
context.BulkInsertOrUpdate(pipes);
```

But I get 

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.SQLite.SQLiteException: database schema has changed
near "0": syntax error

I think it is about providing composite key. When I use Entity Framework's `AddOrUpdate()` I provide three table keys:  `MaterialName`, `ScheduleCode`, `NominalSizeInches`. But when using `BulkInsertOrUpdate` I couldn't find a way to provide table keys.

I read the README, but no information about this in there. How can I perform bulk insert or update in this scenario? Isn't it supported?

**Comment by tiagoln** [comment] 2017-09-20 16:08
Is the table explicitly mapped to an object on your model on your entity framework configuration? In your first example you are using an anonymous object, can you post your 'pipe' object class here for me to see?

**Comment by ferittuncer** [comment] 2017-09-21 13:14
All three keys are strings and not auto incremented.
```
public class Pipe 
    {
        [Key, Column(Order = 0)]
        public String MaterialName { get; set; }

        [Key, Column(Order = 1)]
        public String ScheduleCode { get; set; }

        [Key, Column(Order = 2)]
        public String NominalSizeInches { get; set; }

        public double _internalRoughnessInches { get; set; }

        public Length InternalRoughness
        {
            get => Length.FromInches(_internalRoughnessInches);
            set => _internalRoughnessInches = value.Inches;
        } 

        public double _innerDiameterInches { get; set; }

        
        public Length InnerDiameter 
        {
            get => Length.FromInches(_innerDiameterInches);
            set => _innerDiameterInches = value.Inches;
        }
        public Length Length { get; set; }

}
```

**Comment by ferittuncer** [comment] 2017-09-21 13:22
Also turning `[Key, Column(Order = 0)]` to `[Key, Column(Order = 0), DatabaseGenerated(DatabaseGeneratedOption.None)]` didn't help. I get the same error.

**Comment by tiagoln** [comment] 2017-09-27 22:29
Sorry for the delay in the response, I'll try to replicate this scenario here to see if I catch this same exception.

**Comment by zredb** [comment] 2017-10-11 02:49
I also enconter this problem, the exception info is as below:
发生了 Npgsql.PostgresException
  HResult=0x80131500
  Message=42883: function object_id(unknown) does not exist
  Source=<无法计算异常源>
  StackTrace:
   at Npgsql.NpgsqlConnector.<DoReadMessage>d__147.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__146.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__146.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__153`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at EFCore.BulkExtensions.TableInfo.CheckHasIdentity(DbContext context)
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, BulkConfig bulkConfig)
   at Meteodyn.FM.Controllers.ProjectController.<>c__DisplayClass32_0.<SaveProjectData>b__0() in 
but I'm not sure that the problem is BulkExtensions or  Npgsql,
below is the code call BulkExtensions:

_context.BulkInsertOrUpdate(masts);

the masts is a list of Mast instance. which code is as below:

 public class Mast: RawData
    {
        public int ProjectId { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
       
        public string Name { get; set; }//  	名称
   }
 
the mapping config code like this:
 builder.Entity<Mast>().ToTable("Mast").HasKey(x => new { x.ProjectId, x.Lat, x.Long, x.TimeStamp });

**Comment by tiagoln** [comment] 2017-10-11 12:46
@ferittuncer I've tested your scenario with SQLServer and it worked as it should, but just now I realized that you're using SQLite, which is not supported, this library is SQLServer only.

**Comment by tiagoln** [comment] 2017-10-11 12:51
@zredb You'll have to add annotations to your class, like the class posted by @ferittuncer before you.
I also noticed that in your configuration you have a TimeStamp key which is not present in your Mast class, is it in the RawData?
```
public class Mast: RawData
{
     [Key, Column(Order = 0)]
     public int ProjectId { get; set; }
     [Key, Column(Order = 1)]
     public double Lat { get; set; }
     [Key, Column(Order = 2)]
     public double Long { get; set; }

     public string Name { get; set; }
}
```

**Comment by tiagoln** [comment] 2017-10-15 05:01
As the original post is using SQLite which is not supported, I'll be closing this issue.

**Closed by tiagoln** 2017-10-15 05:01 UTC
